diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/etc/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
user.name=WladimirParraga
user.email=rparragal@uteq.edu.ec
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/WladimirParraga/Turismo.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=parraga
branch.master.merge=refs/heads/master
remote.github.url=https://github.com/WladimirParraga/Turismo.git
remote.github.fetch=+refs/heads/*:refs/remotes/github/*
remote.parraga.url=https://github.com/WladimirParraga/Lugar.git
remote.parraga.fetch=+refs/heads/*:refs/remotes/parraga/*
